// Auto-generated by tests/ui/esm-render.mjs — maps the plugin's imports onto
// the local stubs. Stub URLs resolve relative to THIS file (portable).
const stub = name => new URL('.stubs/' + name, import.meta.url).href
const STUB_URLS = {
  '@hermes/plugin-sdk': stub('sdk.mjs'),
  react: stub('react.mjs'),
  'react/jsx-runtime': stub('jsx-runtime.mjs')
}
export function resolve(specifier, context, nextResolve) {
  if (STUB_URLS[specifier]) {
    return { url: STUB_URLS[specifier], shortCircuit: true }
  }
  return nextResolve(specifier, context)
}
